name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy)$(DayOfYear).$(BuildCounter)

parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    displayName: "Continue even if resources are getting destroyed"
    type: boolean
    default: false
    
  - name: vNext
    displayName: "Run the vNext Path"
    type: boolean
    default: true

trigger:
  - main
  - release/*

pool: $(WindowsPool) 

variables:
  - name: BuildConfiguration
    value: "release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: WindowsPool
    value: "NautilusBuild"
  - name: Container
    value: "ukhydrographicoffice/terraform-azure-powershell-unzip:1.4.4"
  - name: DeploymentPool
    value: "UKHO Ubuntu 1804"
  - name: DeploymentPoolFT
    value: "Tiberius"
  - name: DeploymentPoolPE
    value: "Private Link Deployments (ENG)"
    
stages:
  - stage: Coverity
    jobs: 
      - job: 
        steps: 
          - script: echo Coverity scanner

  - stage: DevDeploy
    jobs:
      - job:
        steps:
        - script: echo Dev deployed
    
  - stage: QADeploy
    dependsOn: DevDeploy
    condition: and(succeeded(), eq('${{ parameters.vNext }}', false))
    jobs:
      - job:
        steps:
        - script: echo QA deployed
    
  - stage: IATDeploy
    dependsOn: DevDeploy
    condition: and(succeeded(), eq('${{ parameters.vNext }}', true))
    jobs:
      - job:
        steps:
        - script: echo IAT deployed
    
  - stage: E2EDeploy
    dependsOn: IATDeploy
    condition: and(succeeded(), eq('${{ parameters.vNext }}', true))
    jobs:
      - job:
        steps:
        - script: echo E2E deployed
    
  - stage: Live
    dependsOn:
    - QADeploy
    - E2EDeploy
    condition: or(succeeded('QADeploy'), and(eq('${{ parameters.vNext }}', true), succeeded('E2EDeploy')))
    jobs:
      - job:
        steps:
        - script: echo Live deployed
    