parameters:
  - name: AzureSubscription
    type: string
  

steps:
  - task: PowerShell@2
    displayName: "Setting KeyVault Secrets as Pipeline Variables "
    inputs:
      targetType: 'inline'
      script: |
          echo "##vso[task.setvariable variable=SapConfiguration.SapPasswordForEncEvent]$(SapPasswordForEncEvent)"
          echo "##vso[task.setvariable variable=SapConfiguration.SapUsernameForEncEvent]$(SapUsernameForEncEvent)"
          echo "##vso[task.setvariable variable=SapConfiguration.SapUsernameForRecordOfSale]$(SapUsernameForRecordOfSale)"
          echo "##vso[task.setvariable variable=SapConfiguration.SapPasswordForRecordOfSale]$(SapPasswordForRecordOfSale)"

  - task: FileTransform@1
    displayName: "File Transform: Mock Service Application Settings"
    condition: and(succeeded(), eq(variables['Environment.Name'], 'ERP-Dev'))
    inputs:
      folderPath: '$(Pipeline.Workspace)/UKHOMockSAPService/*.zip'
      fileType: 'json'
      targetFiles: '**/appsettings.json'

  - task: AzureWebApp@1
    displayName: "Azure App Deploy: ERPFacade-SAP-MockService"
    condition: and(succeeded(), eq(variables['Environment.Name'], 'ERP-Dev'))
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(MOCK_WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/UKHOMockSAPService/UKHO.SAP.MockAPIService.zip"

  - task: FileTransform@1
    displayName: "File Transform: WebAppSettings"
    inputs:
      folderPath: '$(Pipeline.Workspace)/UKHOERPFacadeAPI/*.zip'
      fileType: 'json'
      targetFiles: '**/appsettings.json'
           
  - task: AzureWebApp@1
    displayName: "Azure App Deploy: Staging slot"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/UKHOERPFacadeAPI/UKHOERPFacadeAPI.zip"
      deployToSlotOrASE: true
      slotName: $(WEB_APP_SLOT_NAME)  
  
  # - task: FileTransform@1
  #   displayName: "File Transform: Adds Mock Service Application Settings"
  #   condition: and(succeeded(), eq(variables['Environment.Name'], 'ERP-Dev'))
  #   inputs:
  #     folderPath: '$(Pipeline.Workspace)/ADDSMock/*.zip'
  #     fileType: 'json'
  #     targetFiles: '**/appsettings.json'

  - task: AzureWebApp@1
    displayName: "Azure App Deploy: AddsMockService"
    condition: and(succeeded(), eq(variables['Environment.Name'], 'ERP-IAT'))
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "erpfacade-iat-addsmockservice"
      package: "$(Pipeline.Workspace)/ADDSMock/ADDSMock.zip"   
      appSettings: |
        WEBSITE_WEBDEPLOY_USE_SCM=false
  
  # - task: PowerShell@2
  #   displayName: "Check the status of production slot"
  #   inputs:
  #     targetType: filePath
  #     filePath: "$(Pipeline.Workspace)/terraformartifact/check_service_status.ps1"
  #     arguments: "-healthEndPointUrl $(ErpFacadeConfiguration.BaseUrl)/health -waitTimeInMinute $(waitTimeInMinute)"
